### ISSUE TITLE
Running error in python3, ubuntu18.04 environment，Where is the problem?

### ISSUE THREAD

**Issue by ericwang321** [mikealfare/bcp#15]
ubuntu 18.04 

1. Use bcp in/out,  both normal

> /opt/mssql-tools/bin/bcp dbo.ip2 out ult2.txt -S 192.168.1.3 -U tmsdb -P 123 -d tmsdb -t',' -c
> 
> Starting copy...
> SQLState = S1000, NativeError = 0
> Error = [Microsoft][ODBC Driver 17 for SQL Server]Warning: BCP import with a format file will convert empty strings in delimited columns to NULL.
> 1000 rows successfully bulk-copied to host-file. Total received: 1000

2.run sql.py. error 

_``sql1.py source code `_
from bcp import BCP, Connection, DataFile
conn = Connection(host='192.168.1.3', driver='mssql', username='tmsdb', password='123')
bcp1 = BCP(conn)
dbfile = DataFile(file_path='111.txt', delimiter=',')
bcp1.load(dbfile, 'dbo.ip2')

```

3.run  python3 sql1.py  error message

> (base) aaa@aaa1:~/edit1/dk$ python3 sql1.py 
> Traceback (most recent call last):
>   File "sql1.py", line 17, in <module>
>     bcp1.load(dbfile, 'dbo.ip2')
>   File "/usr/local/lib/python3.6/dist-packages/bcp/core.py", line 61, in load
>     return load.execute()
>   File "/usr/local/lib/python3.6/dist-packages/bcp/dialects/mssql.py", line 81, in execute
>     subprocess.run(f'bcp {self.command}', check=True)
>   File "/usr/local/lib/python3.6/dist-packages/bcp/dialects/mssql.py", line 92, in command
>     return f'{self.table} in "{self.file.path}" {self.connection} {self.config} {self.logging} {self.error}'
>   File "/usr/local/lib/python3.6/dist-packages/bcp/files.py", line 56, in path
>     return self.file.absolute()
**> AttributeError: 'str' object has no attribute 'absolute'**

4. Where is the general problem?

Is it possible to correct the readme file.
Add examples of parameters such as database name, char, and batch.
bcp dbo.ip2 in ult2.txt -S 192.168.1.3 -U tmsdb -P 123 -d tmsdb -t',' -c -b 3

Looking forward to your reply, thank you!

**Comment by mikealfare** [comment]
Good catch. The readme is incorrect. DataFile() is expecting a Path object, not a string. I should probably handle that in the class itself and allow a string to be passed in. In the meantime, import pathlib.Path and wrap your file_path in Path().

**Comment by ericwang321** [comment]
Added path lib, the operation is still wrong, compared to the bcp command line, found that Python BCP originally lacked the database option -d.


hope there is time to change the readme. Thank you!

**Comment by ari-bradharker** [comment]
Hey Eric, I have been able to follow what you and Mike are discussing and am wondering what you mean by "solved by directly adjusting the bcp command line through python"?  You are changing the output from the library and then calling the execution?

**Comment by ericwang321** [comment]
Python directly calls the external command /opt /mssql/bin/bcp....

**Comment by ericwang321** [comment]
temp close issue.

**Comment by myahl** [comment]
@ericwang321 I don't understand how to specify the database option either.

> Added path lib, the operation is still wrong, compared to the bcp command line, found that Python BCP originally **_lacked the database option -d._**
> currently it is solved by directly adjusting the bcp command line through python.

This doesn't really clear it up for me.
>Python directly calls the external command /opt/mssql-tools/bin/bcp....

What exactly do I need to do in order to specify the database?

Edit: Never mind. I see in the tests that you're specifying it as part of the table name `database.schema.table`. This could probably be made clearer in the docs though.

**Comment by mikealfare** [comment]
@myahl You're correct, I should add that to the docs. I also have an outstanding issue (#11) to specify it on the Connection instance. I might actually get to that in the next few weeks.
